using System;
using System.Collections.Generic;
using System.Text;

namespace EO_JS.Helper
{
	// Class to save icon data
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	public static class IconFont
	{
		public const string ArrowLeft = "\U000f004d";
		public const string HeartOutline = "\U000f02d5";
		public const string Heart = "\U000f02d1";
		public const string HeartRemove = "\U000f1430";
		public const string Magnify = "\U000f0349";
		public const string Home = "\U000f02dc";
		public const string Close = "\U000f0156";
		public const string Logout = "\U000f0343";
	}
}
